### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by TimvdLippe** [WISVCH/flitcie-api#4]
I wanted to load the client via HTTPS, but got the following error:

```
Mixed Content: The page at 'https://127.0.0.1:8081/' was loaded over HTTPS, but requested an insecure resource 'http://10.54.0.4:8080/boards'. This request has been blocked; the content must be served over HTTPS.
```

Could you install a certificate for this application such that I can load it over https?

**Comment by praseodym** [comment]
It’s just a dev thing for now, so please don’t expect a production-grade setup with HTTPS.
